name: Deploy Docs

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/gh-pages.yml'
permissions:
  contents: write
env:
  DEPLOY_PLATFORM: 'github'
  VITE_BASE: ${{ github.event.repository.name }}
  SITE_URL: https://${{github.actor}}.github.io
jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.1
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
          DEPLOY_PLATFORM: github
        run: |-
          pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
